# Generated by Django 4.2.4 on 2023-12-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
