# Generated by Django 4.2.4 on 2024-01-28 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0009_alter_post_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileBackground', models.ImageField(blank=True, default='defaultBackground.jpg', upload_to='profile_images/')),
                ('profileImg', models.ImageField(blank=True, default='defaultUser.jpg', upload_to='profile_images/')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('pronouse', models.CharField(blank=True, max_length=15, null=True)),
                ('bio', tinymce.models.HTMLField()),
                ('location', models.CharField(max_length=50)),
                ('doj', models.DateField(auto_now_add=True)),
                ('link_instagram', models.URLField(max_length=150)),
                ('link_x', models.URLField(max_length=150)),
                ('link_github', models.URLField(max_length=150)),
                ('link_telegram', models.URLField(max_length=150)),
                ('followers', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
