# Generated by Django 4.2.4 on 2024-01-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='link_github',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='link_instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='pronouse',
            new_name='pronoun',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='link_telegram',
            new_name='telegram',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='link_x',
            new_name='x',
        ),
    ]
