# Generated by Django 4.2.4 on 2024-03-02 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmarked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
