# Generated by Django 4.2.4 on 2024-03-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_post_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileBackground',
            field=models.ImageField(blank=True, default='profile_images/defaultBackground.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImg',
            field=models.ImageField(blank=True, default='profile_images/defaultUser.jpg', upload_to='profile_images/'),
        ),
    ]
