# Generated by Django 4.2.4 on 2024-04-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isDraft',
            field=models.BooleanField(default=False),
        ),
    ]
