# Generated by Django 4.2.4 on 2024-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_isdraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='defaultBackground.jpg', upload_to='posts_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileBackground',
            field=models.ImageField(blank=True, default='defaultBackground.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profileImg',
            field=models.ImageField(blank=True, default='defaultUser.jpg', upload_to='profile_images/'),
        ),
    ]
